module.exports = {
  appId: 'com.th3rdai.code-companion',
  productName: 'Code Companion',
  copyright: 'Copyright © 2026 James Avila / Th3rdAI',
  directories: { output: 'release' },
  asar: false,
  files: [
    'dist/**/*',
    'lib/**/*',
    'mcp/**/*',
    'server.js',
    'mcp-server.js',
    'startup.sh',
    'deploy.sh',
    'rebuild.sh',
    'cert/README.txt',
    'electron/**/*',
    'resources/**/*',
    'package.json',
    'node_modules/**/*',
    // Never package user config or secrets (PAT, tokens, etc.)
    '!.cc-config.json',
    '!CodeCompanion-Data',
    '!.env',
    '!.env.local',
    '!node_modules/@playwright/**/*',
    '!node_modules/playwright/**/*',
    '!node_modules/playwright-core/**/*',
    '!node_modules/electron/**/*',
    '!src/**/*',
    '!test/**/*',
    '!tests/**/*',
    '!.planning/**/*',
    '!landing/**/*',
    '!MAKER_framework/**/*',
    '!test-results/**/*',
    '!scripts/**/*',
    '!journal/**/*',
    '!design-system/**/*',
    '!.playwright-mcp/**/*',
  ],
  mac: {
    target: ['dmg', 'zip'],
    icon: 'resources/icon.png',
    category: 'public.app-category.developer-tools',
    // Skip code signing entirely until Apple Developer account is configured
    // Users must right-click → Open on first launch to bypass Gatekeeper
    // When ready, uncomment and configure:
    // hardenedRuntime: true,
    // entitlements: 'resources/entitlements.mac.plist',
    // entitlementsInherit: 'resources/entitlements.mac.inherit.plist',
    // identity: 'Developer ID Application: Th3rdAI (TEAM_ID)',
    // notarize: { teamId: 'TEAM_ID' },
    identity: null,
    gatekeeperAssess: false,
  },
  dmg: {
    background: 'resources/dmg-background.png',
    contents: [
      { x: 130, y: 220 },
      { x: 410, y: 220, type: 'link', path: '/Applications' },
    ],
  },
  win: {
    target: ['nsis', 'zip'],
    icon: 'resources/icon.png',
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    installerIcon: 'resources/icon.ico',
    uninstallerIcon: 'resources/icon.ico',
    installerHeaderIcon: 'resources/icon.ico',
    license: 'LICENSE',
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'Code Companion',
    runAfterFinish: true,
    installerSidebar: 'resources/nsis-sidebar.bmp',
    uninstallerSidebar: 'resources/nsis-sidebar.bmp',
  },
  linux: {
    target: ['AppImage', 'zip'],
    icon: 'resources/icon.png',
    category: 'Development',
  },
  publish: {
    provider: 'github',
    owner: 'th3rdai',
    repo: 'CodeCompanion',
  },
  extraResources: [
    { from: 'resources/data-readme.txt', to: 'data-readme.txt' },
  ],
};
