/**
 * License Manager for Code Companion Pro
 *
 * Single source of truth for license state, tier validation, and feature gating.
 * Uses Ed25519 offline-verifiable license keys — no license server required.
 *
 * Supports both tier-based (legacy) and feature-based licensing:
 * - Legacy keys: { email, tier: 'pro', exp, nonce } → grants all pro features
 * - Feature keys: { email, features: ['skillz','agentic'], exp, nonce } → grants specific features
 *
 * GSD-inspired: FEATURE_TIERS is a declarative registry. Adding a new premium
 * feature = adding one line to this object. Nothing else changes.
 */

const crypto = require('crypto');
const { getConfig, updateConfig } = require('./config');

// ── Ed25519 Public Key (embedded in app) ────────────
// Generated by: node scripts/generate-license-key.js --generate-keypair
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAz3/3pkaOcRzJUb1TtL0TUELPGWOT7K+HvnCVq9evdQU=
-----END PUBLIC KEY-----`;

// ── Feature Tier Registry (GSD-inspired declarative pattern) ──
// Adding a new premium feature = adding one line here.

const FEATURE_TIERS = {
  // Free tier modes
  'mode:chat': 'free',
  'mode:explain': 'free',
  'mode:bugs': 'free',
  'mode:refactor': 'free',
  'mode:translate-tech': 'free',
  'mode:translate-biz': 'free',
  'mode:review': 'free',
  'mode:prompting': 'free',
  // Pro tier modes
  'mode:skillz': 'pro',
  'mode:agentic': 'pro',
  'mode:create': 'free',
  'mode:build': 'free',
};

const TRIAL_DAYS = 14;

// ── Internal state ──────────────────────────────────

let _licenseState = null;

// ── Helpers ─────────────────────────────────────────

function _getProFeatures() {
  return Object.entries(FEATURE_TIERS)
    .filter(([, tier]) => tier === 'pro')
    .map(([id]) => id.replace('mode:', ''));
}

// ── Initialize ──────────────────────────────────────

function initLicense() {
  const config = getConfig();
  const license = config.license || {};

  _licenseState = {
    key: license.key || null,
    tier: 'free',
    features: license.features || [],
    source: license.source || null,
    activatedAt: license.activatedAt || null,
    expiresAt: license.expiresAt || null,
    trialStartedAt: license.trialStartedAt || null,
  };

  // Resolve tier and features from stored state
  if (_licenseState.key) {
    const validation = validateKey(_licenseState.key);
    if (validation.valid) {
      _licenseState.tier = validation.tier;
      _licenseState.expiresAt = validation.expiresAt;
      _licenseState.features = validation.features || _getProFeatures();
    } else {
      // Key expired or invalid — revert to free
      _licenseState.key = null;
      _licenseState.tier = 'free';
      _licenseState.features = [];
      _licenseState.source = null;
      _persistLicense();
    }
  } else if (_licenseState.source === 'appstore') {
    // App store purchases don't use keys
    _licenseState.tier = 'pro';
    _licenseState.features = _getProFeatures();
  } else if (_licenseState.trialStartedAt) {
    const trialDays = _getTrialDaysLeft();
    if (trialDays > 0) {
      _licenseState.tier = 'pro';
      _licenseState.source = 'trial';
      _licenseState.features = _getProFeatures();
    } else {
      // Trial expired — clear stale features from config
      _licenseState.features = [];
    }
  }

  return _licenseState;
}

// ── Key Validation ──────────────────────────────────

function validateKey(key) {
  try {
    if (!key || typeof key !== 'string') {
      return { valid: false, error: 'No key provided' };
    }

    // Strip CC-PRO- prefix
    const stripped = key.startsWith('CC-PRO-') ? key.slice(7) : key;
    const dotIndex = stripped.lastIndexOf('.');
    if (dotIndex === -1) {
      return { valid: false, error: 'Invalid key format' };
    }

    const payloadB64 = stripped.slice(0, dotIndex);
    const signatureB64 = stripped.slice(dotIndex + 1);

    // Verify Ed25519 signature
    const signature = Buffer.from(signatureB64, 'base64url');
    const isValid = crypto.verify(null, Buffer.from(payloadB64), PUBLIC_KEY, signature);
    if (!isValid) {
      return { valid: false, error: 'Invalid signature' };
    }

    // Parse and validate payload
    const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString());

    if ((!payload.tier && !payload.features) || !payload.exp) {
      return { valid: false, error: 'Incomplete payload' };
    }

    const expiresAt = new Date(payload.exp);
    if (isNaN(expiresAt.getTime())) {
      return { valid: false, error: 'Invalid expiry date' };
    }

    if (expiresAt < new Date()) {
      return { valid: false, error: 'License expired' };
    }

    return {
      valid: true,
      tier: payload.tier || 'pro',
      features: payload.features || null,
      email: payload.email,
      expiresAt: payload.exp,
    };
  } catch (err) {
    return { valid: false, error: `Validation failed: ${err.message}` };
  }
}

// ── Public API ──────────────────────────────────────

function getTier() {
  if (!_licenseState) initLicense();
  return _licenseState.tier;
}

function getLicenseInfo() {
  if (!_licenseState) initLicense();
  return {
    tier: _licenseState.tier,
    features: _licenseState.features || [],
    source: _licenseState.source,
    expiresAt: _licenseState.expiresAt,
    trialDaysLeft: _getTrialDaysLeft(),
    trialAvailable: !_licenseState.trialStartedAt,
  };
}

function getEnabledFeatures() {
  if (!_licenseState) initLicense();
  return _licenseState.features || [];
}

function activateLicense(key) {
  const validation = validateKey(key);
  if (!validation.valid) {
    return { success: false, error: validation.error };
  }

  _licenseState.key = key;
  _licenseState.tier = validation.tier;
  _licenseState.features = validation.features || _getProFeatures();
  _licenseState.source = 'direct';
  _licenseState.activatedAt = new Date().toISOString();
  _licenseState.expiresAt = validation.expiresAt;
  _persistLicense();

  return { success: true, tier: validation.tier, expiresAt: validation.expiresAt };
}

function deactivateLicense() {
  _licenseState.key = null;
  _licenseState.tier = 'free';
  _licenseState.features = [];
  _licenseState.source = null;
  _licenseState.activatedAt = null;
  _licenseState.expiresAt = null;
  _persistLicense();

  return { success: true, tier: 'free' };
}

function startTrial() {
  if (_licenseState.trialStartedAt) {
    return { success: false, error: 'Trial already used' };
  }
  if (_licenseState.tier === 'pro') {
    return { success: false, error: 'Already on Pro tier' };
  }

  _licenseState.trialStartedAt = new Date().toISOString();
  _licenseState.tier = 'pro';
  _licenseState.features = _getProFeatures();
  _licenseState.source = 'trial';
  _persistLicense();

  return { success: true, tier: 'pro', trialDaysLeft: TRIAL_DAYS };
}

function handleAppStorePurchase() {
  _licenseState.tier = 'pro';
  _licenseState.features = _getProFeatures();
  _licenseState.source = 'appstore';
  _licenseState.activatedAt = new Date().toISOString();
  _licenseState.expiresAt = null; // App store purchases don't expire via key
  _persistLicense();

  return { success: true, tier: 'pro', source: 'appstore' };
}

function isFeatureAllowed(featureId) {
  if (!_licenseState) initLicense();
  const requiredTier = FEATURE_TIERS[featureId];
  if (!requiredTier) return true; // Unknown features default to allowed
  if (requiredTier === 'free') return true;
  const feature = featureId.replace(/^mode:/, '');
  // Feature-based model: when features is defined (even []), use it exclusively
  if (_licenseState.features !== undefined) {
    return _licenseState.features.includes(feature);
  }
  // Legacy fallback: features undefined = old tier-only state
  return _licenseState.tier === 'pro';
}

// ── Internal Helpers ────────────────────────────────

function _getTrialDaysLeft() {
  if (!_licenseState?.trialStartedAt) return 0;
  const started = new Date(_licenseState.trialStartedAt);
  const elapsed = (Date.now() - started.getTime()) / (1000 * 60 * 60 * 24);
  return Math.max(0, Math.ceil(TRIAL_DAYS - elapsed));
}

function _persistLicense() {
  updateConfig({
    license: {
      key: _licenseState.key,
      tier: _licenseState.tier,
      features: _licenseState.features || [],
      source: _licenseState.source,
      activatedAt: _licenseState.activatedAt,
      expiresAt: _licenseState.expiresAt,
      trialStartedAt: _licenseState.trialStartedAt,
    },
  });
}

module.exports = {
  FEATURE_TIERS,
  TRIAL_DAYS,
  initLicense,
  validateKey,
  getTier,
  getLicenseInfo,
  getEnabledFeatures,
  activateLicense,
  deactivateLicense,
  startTrial,
  handleAppStorePurchase,
  isFeatureAllowed,
};
